# Generated by Django 5.1.15 on 2026-09-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "api_keys",
            "0003_apikeyauditlog_actor_label_apikeyauditlog_actor_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="all_workspace_accounts",
            field=models.BooleanField(
                default=False,
                help_text="When true the key may act on EVERY account in its workspace, including ones connected after the key was issued, and the explicit allowlist is ignored. Used by provisioned keys (apps/api/routers/provision.py) where a contractor connects accounts after their workspace and key already exist.",
            ),
        ),
    ]
