# Generated by Django 5.1.15 on 2026-09-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectionlink",
            name="return_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
